// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sportify;

#nullable disable

namespace Sportify.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706074026_AddGymClassesAndOffers")]
    partial class AddGymClassesAndOffers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sportify.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BrandID");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandID = 1,
                            CreatedBy = "Admin",
                            Description = "The world’s largest sportswear brand",
                            LogoURL = "https://tse4.mm.bing.net/th/id/OIP.xRP_6PtMGwc6UGslxaK4YAHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
                            Name = "Nike"
                        },
                        new
                        {
                            BrandID = 2,
                            CreatedBy = "Admin",
                            Description = "German sportswear company.",
                            LogoURL = "https://tse3.mm.bing.net/th/id/OIP.aw4ynosen6elgMpjUjaUBwHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
                            Name = "Adidas"
                        },
                        new
                        {
                            BrandID = 3,
                            CreatedBy = "Admin",
                            Description = "German sportswear company.",
                            LogoURL = "https://tse2.mm.bing.net/th/id/OIP.0z2kSI_ehJizOeLLUL77dQHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
                            Name = "Puma"
                        },
                        new
                        {
                            BrandID = 4,
                            CreatedBy = "Admin",
                            Description = "Sportswear",
                            LogoURL = "https://tse3.mm.bing.net/th/id/OIP.tASbMfiMM2xaVjJfhDk3QgHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
                            Name = "Jordan"
                        },
                        new
                        {
                            BrandID = 5,
                            CreatedBy = "Admin",
                            Description = "Electronics manufacturer.",
                            LogoURL = "https://tse3.mm.bing.net/th/id/OIP.w4RV1Nk4yYTvavsPKmXknwHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
                            Name = "Sony"
                        });
                });

            modelBuilder.Entity("Sportify.Models.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartID"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CartID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            CartID = 1,
                            UserID = 1
                        },
                        new
                        {
                            CartID = 2,
                            UserID = 2
                        },
                        new
                        {
                            CartID = 3,
                            UserID = 3
                        });
                });

            modelBuilder.Entity("Sportify.Models.CartItem", b =>
                {
                    b.Property<int>("CartID")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartID", "ProductVariantId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Sportify.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ParentCategoryID")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            Description = "All types items for men",
                            Name = "Men"
                        },
                        new
                        {
                            CategoryID = 2,
                            Description = "All types of items for women",
                            Name = "Women's"
                        },
                        new
                        {
                            CategoryID = 3,
                            Description = "Equipments for sports",
                            Name = "Equipments"
                        },
                        new
                        {
                            CategoryID = 4,
                            Description = "Sports",
                            Name = "Sports"
                        },
                        new
                        {
                            CategoryID = 5,
                            Description = "Clothing for men.",
                            Name = "Men's Clothing",
                            ParentCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 6,
                            Description = "Footwear for men.",
                            Name = "Men's Footwear",
                            ParentCategoryID = 1
                        },
                        new
                        {
                            CategoryID = 7,
                            Description = "Clothing for women.",
                            Name = "Women's Clothing",
                            ParentCategoryID = 2
                        },
                        new
                        {
                            CategoryID = 8,
                            Description = "Footwear for women.",
                            Name = "Women's Footwear",
                            ParentCategoryID = 2
                        },
                        new
                        {
                            CategoryID = 9,
                            Description = "Earphones and  others",
                            Name = "Headwears",
                            ParentCategoryID = 3
                        },
                        new
                        {
                            CategoryID = 10,
                            Description = "Things like handgrips",
                            Name = "Others",
                            ParentCategoryID = 3
                        },
                        new
                        {
                            CategoryID = 11,
                            Description = "FootBall items",
                            Name = "FootBall",
                            ParentCategoryID = 4
                        },
                        new
                        {
                            CategoryID = 12,
                            Description = "BasketBall items",
                            Name = "BasketBall",
                            ParentCategoryID = 4
                        },
                        new
                        {
                            CategoryID = 13,
                            Description = "Tennis items",
                            Name = "Tennis",
                            ParentCategoryID = 4
                        },
                        new
                        {
                            CategoryID = 14,
                            Description = "Running items",
                            Name = "Running",
                            ParentCategoryID = 4
                        },
                        new
                        {
                            CategoryID = 15,
                            Description = "Gym items",
                            Name = "Gym",
                            ParentCategoryID = 4
                        });
                });

            modelBuilder.Entity("Sportify.Models.GymAd", b =>
                {
                    b.Property<int>("GymAdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GymAdId"));

                    b.Property<string>("AboutUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GymName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdminCreated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GymAdId");

                    b.HasIndex("UserID");

                    b.ToTable("GymAds");
                });

            modelBuilder.Entity("Sportify.Models.GymClass", b =>
                {
                    b.Property<int>("GymClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GymClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GymAdId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURLs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GymClassId");

                    b.HasIndex("GymAdId");

                    b.ToTable("GymClasses");
                });

            modelBuilder.Entity("Sportify.Models.GymOffer", b =>
                {
                    b.Property<int>("GymOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GymOfferId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscountText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GymAdId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("GymOfferId");

                    b.HasIndex("GymAdId");

                    b.ToTable("GymOffers");
                });

            modelBuilder.Entity("Sportify.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FastShiping")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShipmentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipmentTrackingNumber")
                        .HasColumnType("int");

                    b.Property<int>("ShippingAddressID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("ShippingAddressID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FastShiping = true,
                            Note = "Leave at door.",
                            PaidAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentAmount = 3600.00m,
                            PaymentMethod = "Card",
                            ShipmentStatus = "Delivered",
                            ShipmentTrackingNumber = 321,
                            ShippingAddressID = 1,
                            Status = "Delivered",
                            UserID = 1
                        },
                        new
                        {
                            OrderId = 2,
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FastShiping = false,
                            Note = "Call before delivery.",
                            PaidAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentAmount = 2200.00m,
                            PaymentMethod = "Cash",
                            ShipmentStatus = "Cancelled",
                            ShipmentTrackingNumber = 123,
                            ShippingAddressID = 2,
                            Status = "Pending",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("Sportify.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductVariantID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderID", "ProductVariantID");

                    b.HasIndex("ProductVariantID");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            ProductVariantID = 1,
                            Quantity = 2
                        },
                        new
                        {
                            OrderID = 2,
                            ProductVariantID = 3,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 1,
                            ProductVariantID = 5,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 1,
                            ProductVariantID = 4,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 2,
                            ProductVariantID = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderID = 2,
                            ProductVariantID = 2,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Sportify.Models.OrderReview", b =>
                {
                    b.Property<int>("OrderReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GoodStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("OnTime")
                        .HasColumnType("bit");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("DECIMAL(2,1)");

                    b.Property<bool>("TheWantedOrder")
                        .HasColumnType("bit");

                    b.HasKey("OrderReviewId");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderReview");

                    b.HasData(
                        new
                        {
                            OrderReviewId = 1,
                            Comment = "Great experience, fast delivery!",
                            GoodStatus = true,
                            OnTime = true,
                            OrderID = 1,
                            Rating = 4.5m,
                            TheWantedOrder = true
                        },
                        new
                        {
                            OrderReviewId = 2,
                            Comment = "Items were correct but arrived late.",
                            GoodStatus = true,
                            OnTime = false,
                            OrderID = 2,
                            Rating = 3.0m,
                            TheWantedOrder = true
                        });
                });

            modelBuilder.Entity("Sportify.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("BrandID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ProductID");

                    b.HasIndex("BrandID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            BrandID = 1,
                            CategoryID = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Description = "Iconic Air Max sneakers.",
                            ImageURL = "https://cdn.example.com/airmax.png",
                            Name = "Nike Air Max"
                        },
                        new
                        {
                            ProductID = 2,
                            BrandID = 2,
                            CategoryID = 6,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Description = "High performance running shoe.",
                            ImageURL = "https://cdn.example.com/ultraboost.png",
                            Name = "Adidas Ultraboost"
                        },
                        new
                        {
                            ProductID = 3,
                            BrandID = 3,
                            CategoryID = 5,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Description = "Casual slim-fit cotton shirt.",
                            ImageURL = "https://cdn.example.com/shirt.png",
                            Name = "Puma Slim Fit Shirt"
                        },
                        new
                        {
                            ProductID = 4,
                            BrandID = 5,
                            CategoryID = 9,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Description = "Latest Sony flagship speakers.",
                            ImageURL = "https://cdn.example.com/s24.png",
                            Name = "Sony Headphones"
                        },
                        new
                        {
                            ProductID = 5,
                            BrandID = 4,
                            CategoryID = 5,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Description = "Iconic Jordan Shorts.",
                            ImageURL = "https://cdn.example.com/iphone15.png",
                            Name = "Jordan Shorts"
                        },
                        new
                        {
                            ProductID = 6,
                            BrandID = 2,
                            CategoryID = 10,
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Admin",
                            Description = "Adidas football",
                            ImageURL = "https://cdn.example.com/iphone15.png",
                            Name = "Adidas ball"
                        });
                });

            modelBuilder.Entity("Sportify.Models.ProductReview", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rating")
                        .HasColumnType("DECIMAL(2,1)");

                    b.Property<int>("ReviewID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductReviews");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            ProductID = 1,
                            Comment = "Best sneakers I've ever bought!",
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0m,
                            ReviewID = 1
                        },
                        new
                        {
                            UserID = 2,
                            ProductID = 2,
                            Comment = "Very comfortable for long runs.",
                            CreatedAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.0m,
                            ReviewID = 2
                        },
                        new
                        {
                            UserID = 1,
                            ProductID = 4,
                            Comment = "Great phone, amazing camera quality.",
                            CreatedAt = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4.5m,
                            ReviewID = 3
                        },
                        new
                        {
                            UserID = 2,
                            ProductID = 6,
                            Comment = "Nice dress but sizing runs small.",
                            CreatedAt = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3.5m,
                            ReviewID = 4
                        },
                        new
                        {
                            UserID = 2,
                            ProductID = 5,
                            Comment = "Incredibly fast laptop, worth every EGP.",
                            CreatedAt = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5.0m,
                            ReviewID = 5
                        });
                });

            modelBuilder.Entity("Sportify.Models.ProductVariant", b =>
                {
                    b.Property<int>("ProductVariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductVariantId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductVariantId");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            ProductVariantId = 1,
                            Color = "White",
                            Price = 1800.00m,
                            ProductID = 1,
                            SKU = "NK-AM-WHT-42",
                            Size = "42",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductVariantId = 2,
                            Color = "Black",
                            Price = 1800.00m,
                            ProductID = 1,
                            SKU = "NK-AM-BLK-43",
                            Size = "43",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductVariantId = 3,
                            Color = "Grey",
                            Price = 2200.00m,
                            ProductID = 2,
                            SKU = "AD-UB-GRY-42",
                            Size = "42",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductVariantId = 4,
                            Color = "Navy",
                            Price = 2200.00m,
                            ProductID = 2,
                            SKU = "AD-UB-NVY-44",
                            Size = "44",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductVariantId = 5,
                            Color = "White",
                            Price = 350.00m,
                            ProductID = 3,
                            SKU = "PM-SH-WHT-M",
                            Size = "M",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductVariantId = 6,
                            Color = "Blue",
                            Price = 350.00m,
                            ProductID = 3,
                            SKU = "PM-SH-BLU-L",
                            Size = "L",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductVariantId = 7,
                            Color = "Phantom Black",
                            Price = 2500.00m,
                            ProductID = 4,
                            SKU = "SH-H200-BLK-256",
                            Size = "N/A",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductVariantId = 8,
                            Color = "Cream",
                            Price = 2700.00m,
                            ProductID = 4,
                            SKU = "SH-H200-CRM-512",
                            Size = "N/A",
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductVariantId = 9,
                            Color = "Pink",
                            Price = 1800.00m,
                            ProductID = 5,
                            SKU = "JD-SHRT-PNK-128",
                            Size = "L",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductVariantId = 10,
                            Color = "Black",
                            Price = 1800.00m,
                            ProductID = 5,
                            SKU = "JD-SHRT-BLK-256",
                            Size = "XL",
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductVariantId = 11,
                            Color = "Blue",
                            Price = 2000.00m,
                            ProductID = 6,
                            SKU = "AD-BL-BLU-WC",
                            Size = "N/A",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductVariantId = 12,
                            Color = "Purple",
                            Price = 2000.00m,
                            ProductID = 6,
                            SKU = "AD-BL-PRPL-WC",
                            Size = "N/A",
                            StockQuantity = 15
                        });
                });

            modelBuilder.Entity("Sportify.Models.ShippingAddress", b =>
                {
                    b.Property<int>("ShippingAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingAddressId"));

                    b.Property<string>("AlternativePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Apartment")
                        .HasColumnType("tinyint");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Building")
                        .HasColumnType("tinyint");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Floor")
                        .HasColumnType("tinyint");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ShippingAddressId");

                    b.HasIndex("UserID");

                    b.ToTable("ShippingAddresses");

                    b.HasData(
                        new
                        {
                            ShippingAddressId = 1,
                            AlternativePhone = "01334567890",
                            Apartment = (byte)10,
                            Area = "Sidi Gaber",
                            Building = (byte)22,
                            City = "Al-Wasta",
                            Country = "Egypt",
                            Floor = (byte)4,
                            Governorate = "BeniSuef",
                            Phone = "01234567891",
                            Street = "Corniche",
                            UserID = 1
                        },
                        new
                        {
                            ShippingAddressId = 2,
                            AlternativePhone = "01198765432",
                            Apartment = (byte)8,
                            Area = "City Center",
                            Building = (byte)7,
                            City = "Al-Fashn",
                            Country = "Egypt",
                            Floor = (byte)3,
                            Governorate = "BeniSuef",
                            Phone = "01234567891",
                            Street = "Main St",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("Sportify.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Address = "Bns",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hager.mahmoud@email.com",
                            FirstName = "Hager",
                            LastName = "Mahmoud",
                            PasswordHash = "hashed_pw_1",
                            Phone = "01234567891",
                            Role = "Admin"
                        },
                        new
                        {
                            UserID = 2,
                            Address = "Bns",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abdelrhman.salah@email.com",
                            FirstName = "Abdelrhman",
                            LastName = "Salah",
                            PasswordHash = "hashed_pw_2",
                            Phone = "01234567891",
                            Role = "Admin"
                        },
                        new
                        {
                            UserID = 3,
                            Address = "Bns",
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "osama.tarek@email.com",
                            FirstName = "Osama",
                            LastName = "Tarek",
                            PasswordHash = "hashed_pw_3",
                            Phone = "01234567891",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Sportify.Models.UserMessage", b =>
                {
                    b.Property<int>("UserMessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserMessageID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserMessageID");

                    b.HasIndex("UserID");

                    b.ToTable("UserMessages");
                });

            modelBuilder.Entity("Sportify.Models.WishlistItem", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Sportify.Models.Cart", b =>
                {
                    b.HasOne("Sportify.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Sportify.Models.Cart", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sportify.Models.CartItem", b =>
                {
                    b.HasOne("Sportify.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sportify.Models.ProductVariant", "ProductVariant")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Sportify.Models.Category", b =>
                {
                    b.HasOne("Sportify.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Sportify.Models.GymAd", b =>
                {
                    b.HasOne("Sportify.Models.User", "User")
                        .WithMany("GymAds")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sportify.Models.GymClass", b =>
                {
                    b.HasOne("Sportify.Models.GymAd", "GymAd")
                        .WithMany("GymClasses")
                        .HasForeignKey("GymAdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymAd");
                });

            modelBuilder.Entity("Sportify.Models.GymOffer", b =>
                {
                    b.HasOne("Sportify.Models.GymAd", "GymAd")
                        .WithMany("GymOffers")
                        .HasForeignKey("GymAdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymAd");
                });

            modelBuilder.Entity("Sportify.Models.Order", b =>
                {
                    b.HasOne("Sportify.Models.ShippingAddress", "ShippingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sportify.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShippingAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sportify.Models.OrderItem", b =>
                {
                    b.HasOne("Sportify.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sportify.Models.ProductVariant", "ProductVariant")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductVariantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Sportify.Models.OrderReview", b =>
                {
                    b.HasOne("Sportify.Models.Order", "Order")
                        .WithMany("OrderReviews")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Sportify.Models.Product", b =>
                {
                    b.HasOne("Sportify.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sportify.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sportify.Models.ProductReview", b =>
                {
                    b.HasOne("Sportify.Models.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sportify.Models.User", "User")
                        .WithMany("ProductReviews")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sportify.Models.ProductVariant", b =>
                {
                    b.HasOne("Sportify.Models.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sportify.Models.ShippingAddress", b =>
                {
                    b.HasOne("Sportify.Models.User", "User")
                        .WithMany("ShippingAddresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sportify.Models.UserMessage", b =>
                {
                    b.HasOne("Sportify.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sportify.Models.WishlistItem", b =>
                {
                    b.HasOne("Sportify.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sportify.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sportify.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Sportify.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Sportify.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Sportify.Models.GymAd", b =>
                {
                    b.Navigation("GymClasses");

                    b.Navigation("GymOffers");
                });

            modelBuilder.Entity("Sportify.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("OrderReviews");
                });

            modelBuilder.Entity("Sportify.Models.Product", b =>
                {
                    b.Navigation("ProductReviews");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("Sportify.Models.ProductVariant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Sportify.Models.ShippingAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Sportify.Models.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("GymAds");

                    b.Navigation("Messages");

                    b.Navigation("Orders");

                    b.Navigation("ProductReviews");

                    b.Navigation("ShippingAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
